[project]
dependencies=[
]
description="Add your description here"
name="python-sf"
readme="README.md"
requires-python=">=3.11"
version="0.1.0"

[build-system]
build-backend="hatchling.build"
requires     =["hatchling"]

[dependency-groups]
dev=["pytest>=8.3.5", "ruff>=0.9.10", "maturin>=1.8.2"]
